From node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY ..

RUN npm run build

FROM node:18-alpine

RUN npm install -g serve

WORKDIR /app

COPY --FROM=builder /app/dist ./dist

EXPOSE 8080

CMD ["serve", "-s", "dist", "-l", "8080"]
