FROM golang:1.14-alpine AS builder

RUN apk add --no-cache git && \
    go get -u github.com/golang/dep/cmd/dep

WORKDIR /go/src/github.com/auth-api

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o auth-api .

FROM alpine:3.12

COPY --from=builder /go/src/github.com/auth-api/auth-api .

CMD ["./auth-api"]
